import Navigation from "@/components/Navigation/Navigation";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SFProDisplay from "./fonts";

import './global.css'
import Header from "@/components/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={SFProDisplay.semibold.className}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {children}
        <Navigation />
      </body>
    </html>
  );
}
